---
name: Authentication Failure Simulation - Auth401
on:
  workflow_dispatch:

jobs:
  authentication-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Authentication Failure
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Attempting login for user: admin"
          sleep 1
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Invalid username and password"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Using default credentials"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
