---
name: CI Cache Corruption Simulation - CACHE01
on:
  workflow_dispatch:

jobs:
  ci-cache-corruption:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate CI Cache Corruption
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Restoring CI cache for job 'build#892'..."
          sleep 1
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Restored cache is corrupted: checksum mismatch"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Rebuilt cache"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
