---
name: CI Job Timeout Simulation - JOBTM01
on:
  workflow_dispatch:

jobs:
  ci-job-timeout:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate CI Job Timeout
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Starting CI pipeline job #481..."
          sleep 10
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] CI job exceeded maximum allowed duration (3600 seconds)"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Reduced job scope to complete"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
