---
name: Cluster Down Simulation - CLSTR01
on:
  workflow_dispatch:

jobs:
  cluster-down:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Cluster Down with Retry
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Connecting to cluster node..."
          RETRY_COUNT=0
          MAX_RETRIES=2
          while true; do
            if [ $RETRY_COUNT -gt 0 ]; then
              echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [WARNING] Cluster connection failed. Retrying ($RETRY_COUNT/$MAX_RETRIES)..."
            fi
            if [ $((RANDOM % 2)) -eq 0 ]; then
              echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Cluster connection successful."
              break
            else
              echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Cluster node not reachable (node-5)"
              RETRY_COUNT=$((RETRY_COUNT + 1))
              if [ $RETRY_COUNT -gt $MAX_RETRIES ]; then
                echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Cluster connection failed after $MAX_RETRIES retries."
                echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 1"
                exit 1
              fi
              sleep 2
            fi
          done
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
