---
name: Compilation Error Simulation - COMP001
on:
  workflow_dispatch:

jobs:
  compilation-error:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Compilation Error
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Compiling module 'core-utils'"
          sleep 2
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Compilation failed: Unexpected token '->' at line"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Using precompiled module"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
