---
name: Disk Full Simulation - DISK100
on:
  workflow_dispatch:

jobs:
  disk-full:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Disk Full
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Writing data to disk"
          sleep 4
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] No space left on device"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Cleared temporary files to free space"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
