---
name: Flaky Test Simulation - Flaky001
on:
  workflow_dispatch:

jobs:
  flaky-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Test Suite
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Running test suite: test_login_functionality"
          RETRY_COUNT=0
          MAX_RETRIES=2
          while true; do
            if [ $RETRY_COUNT -gt 0 ]; then
              echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [WARNING] Test failed, retrying ($RETRY_COUNT/$MAX_RETRIES)..."
            fi
            if [ $((RANDOM % 2)) -eq 0 ]; then
              echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Test passed on attempt $((RETRY_COUNT + 1))"
              break
            else
              echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Test 'test_login_functionality' failed"
              RETRY_COUNT=$((RETRY_COUNT + 1))
              if [ $RETRY_COUNT -gt $MAX_RETRIES ]; then
                echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Test failed after $MAX_RETRIES retries."
                echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 1"
                exit 1
              fi
              sleep 2
            fi
          done
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
