---
name: Infinite Loop Simulation - INFLOOP
on:
  workflow_dispatch:

jobs:
  infinite-loop:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Infinite Loop
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Executing processing routine..."
          sleep 10
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [WARNING] Task running longer than expected"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Terminated task early to avoid infinite loop"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
