---
name: Invalid Input Simulation - INPUT01
on:
  workflow_dispatch:

jobs:
  invalid-input:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Invalid Input
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Parsing CLI arguments..."
          sleep 1
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Invalid input: '--threads=-1' is not allowed"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Using default arguments"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
