---
name: Memory Leak Simulation - MEMLEAK
on:
  workflow_dispatch:

jobs:
  memory-leak:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Memory Leak
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Monitoring memory usage for service..."
          sleep 10
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [WARNING] Memory usage at 85%"
          sleep 10
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [WARNING] Memory usage at 92%"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Suspected memory leak: usage reached 97%"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Restarted service to clear memory"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
