---
name: Merge Conflict Simulation - GITMERGE
on:
  workflow_dispatch:

jobs:
  merge-conflict:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Merge Conflict
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Merging feature branch into 'main'..."
          sleep 2
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Merge conflict detected in 'app/routes.py'"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Resolved conflict automatically"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
