---
name: Missing Configuration Simulation - CFG404
on:
  workflow_dispatch:

jobs:
  missing-configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Missing Configuration
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Reading configuration from 'config.yaml'..."
          sleep 1
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Missing configuration value: 'db.connection_string'"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Using default configuration"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
