---
name: Package Install Failure Simulation - PKGINST
on:
  workflow_dispatch:

jobs:
  package-install-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Package Install Failure
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Installing system packages..."
          sleep 3
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Failed to install package 'libxml2': dependency not met"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Using alternative package"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
