---
name: Permission Denied Simulation - PERM403
on:
  workflow_dispatch:

jobs:
  permission-denied:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Permission Denied
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Accessing file '/etc/app/config.yaml'..."
          sleep 1
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Permission denied while reading config file"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Using alternative file path"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
