---
name: Scheduler Missed Simulation - SCHEDMIS
on:
  workflow_dispatch:

jobs:
  scheduler-missed:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Scheduler Missed
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Scheduled task 'daily_backup' expected at 02:00..."
          sleep 1
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Task missed scheduled window due to system downtime"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Rescheduled task"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
