---
name: Signal Interrupt Simulation - SIGINT
on:
  workflow_dispatch:

jobs:
  signal-interrupt:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Signal Interrupt
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Launching background process..."
          sleep 7
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [WARNING] Received interrupt signal (SIGINT)"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Gracefully shut down process"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
