---
name: Test Runner Crash Simulation - TSTCRSH
on:
  workflow_dispatch:

jobs:
  test-runner-crash:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Test Runner Crash
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Starting unit test run..."
          sleep 2
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Test runner crashed with segmentation fault"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Restarted test runner"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
