---
name: Zombie Process Simulation - ZOMB001
on:
  workflow_dispatch:

jobs:
  zombie-process:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Zombie Process
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Cleaning up completed jobs..."
          sleep 3
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Zombie process detected: PID 10234 not reaped"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Reaped zombie process"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"

rules:
  - match: "npm ERR!"
    fix: "npm cache clean --force && npm install"
  - match: "ModuleNotFoundError"
    fix: "pip install -r requirements.txt"
  - match: "EADDRINUSE"
    fix: "killall node"
  - match: "command not found"
    fix: "echo 'Install missing CLI tool manually'"
  - match: "Failed to compile"
    fix: "Check for syntax errors or missing dependencies"
