---
name: Compilation Error Simulation - COMP001
on:
  workflow_dispatch:

jobs:
  compilation-error:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Compilation Error
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Compiling module 'core-utils'"
          sleep 2
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Compilation failed: Unexpected token '->' at line"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Using precompiled module"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"
