---
name: Disk Full Simulation - DISK100
on:
  workflow_dispatch:

jobs:
  disk-full:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Disk Full
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Writing data to disk"
          sleep 4
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] No space left on device"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Cleared temporary files to free space"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"
