---
name: DNS Resolution Failure Simulation - DNS0001
on:
  workflow_dispatch:

jobs:
  dns-resolution-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate DNS Resolution Failure with Retry
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Performing DNS lookup for service endpoint..."
          RETRY_COUNT=0
          MAX_RETRIES=2
          while true; do
            if [ $RETRY_COUNT -gt 0 ]; then
              echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [WARNING] DNS lookup failed. Retrying ($RETRY_COUNT/$MAX_RETRIES)..."
            fi
            if [ $((RANDOM % 2)) -eq 0 ]; then
              echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] DNS lookup successful."
              break
            else
              echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] DNS lookup failed for service: host not found"
              RETRY_COUNT=$((RETRY_COUNT + 1))
              if [ $RETRY_COUNT -gt $MAX_RETRIES ]; then
                echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] DNS lookup failed after $MAX_RETRIES retries."
                echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 1"
                exit 1
              fi
              sleep 2
            fi
          done
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"
