---
name: File Not Found Simulation - file404
on:
  workflow_dispatch:

jobs:
  file-not-found:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate File Not Found
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Opening configuration file: /app/config.yaml"
          sleep 1
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] File not found: /app/config.yaml"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Using default configuration"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"
