---
name: Missing Dependency Simulation - DEP404
on:
  workflow_dispatch:

jobs:
  missing-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Missing Dependency
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Loading module 'libcrypto'"
          sleep 1
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Required dependency 'libcrypto' not found"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Using alternative module"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"
