---
name: Missing Configuration Simulation - CFG404
on:
  workflow_dispatch:

jobs:
  missing-configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Missing Configuration
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Reading configuration from 'config.yaml'..."
          sleep 1
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Missing configuration value: 'db.connection_string'"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Using default configuration"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"
