---
name: Pod Crash Simulation - PODFAIL
on:
  workflow_dispatch:

jobs:
  pod-crash:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Pod Crash
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Deploying Kubernetes pod 'auth-service'..."
          sleep 3
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] Pod 'auth-service' crashed due to OOMKilled"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Restarted pod with adjusted resources"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"
