---
name: Test Assertion Failure Simulation - TESTF01
on:
  workflow_dispatch:

jobs:
  test-assertion-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Test Assertion Failure
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Running test case 'test_user_creation'..."
          sleep 1
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [ERROR] AssertionError: Expected user count = 3, got 2"
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Fallback: Adjusted test expectations"
      - name: Exit with Success
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') [INFO] Exiting with status 0"
